server:
  port: 12101
spring:
  application:
    name: gateway-user
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
      routes:
        - id: freshwater_goods_route
          #uri: http://localhost:18026
          uri: lb://goods
          predicates:
            - Host=www.freshwater.com**
            # - Path=/brand/**
          filters:
            # - PrefixPath=/brand
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:11101/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true